export const CHANGE_MAP_CITY = "CHANGE_MAP_CITY"

export const CHANGE_WEATHER_CITY = "CHANGE_WEATHER_CITY"

export const DELETE_CITY = "DELETE_CITY"

export const TOGGLE_CITY = "TOGGLE_CITY"

export const UPDATE_DIRECTION = "UPDATE_DIRECTION"

export const SET_HEADER = "SET_HEADER"

export const SET_NOW_WEATHER = 'SET_NOW_WEATHER'

export const SET_FUTURE_WEATHER = 'SET_FUTURE_WEATHER'