export const CHANGE_CITY = "CHANGE_CITY"

export const DELETE_CITY = "DELETE_CITY"

export const TOGGLE_CITY = "TOGGLE_CITY"

export const UPDATE_DIRECTION = "UPDATE_DIRECTION"

export const SET_TITLE = "SET_TITLE"

export const SET_RIGHT_OPTION = 'SET_RIGHT_OPTION'

export const SET_NOW_WEATHER = 'SET_NOW_WEATHER'

export const SET_FUTURE_WEATHER = 'SET_FUTURE_WEATHER'